# Generated by Django 4.2.6 on 2023-11-14 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('text_price', models.CharField(max_length=100, verbose_name='Kurs narxi(yozuv bilan)')),
                ('status', models.BooleanField(default=True)),
                ('for_bot', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=200)),
                ('about', models.TextField(verbose_name='Kurs xaqtida')),
                ('code_for_certificate', models.CharField(max_length=50, verbose_name='sartifikat uchun maxsus kod')),
                ('image', models.ImageField(upload_to='courses')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('capacity', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'specializations',
            },
        ),
        migrations.CreateModel(
            name='KeldiKetdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.PositiveIntegerField()),
                ('full_name', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=3)),
                ('event_datetime', models.TimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keldi_ketdi', to='administration.organizations')),
            ],
            options={
                'db_table': 'keldi_ketdi',
            },
        ),
    ]
