# Generated by Django 4.2.6 on 2023-11-14 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('Naqd', 'Naqd'), ('Paynet', 'Paynet'), ('Payme', 'Payme'), ('Click', 'Click'), ('Terminal', 'Terminal'), ('Bank', 'Bank')], max_length=10)),
                ('description', models.TextField()),
                ('purpose', models.IntegerField()),
                ('month', models.IntegerField(choices=[(1, 'Yanvar'), (2, 'Fevral'), (3, 'Mart')])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='school.groups')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='school.students')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
