# Generated by Django 4.2.6 on 2023-11-14 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Arizachining ism-familyasi')),
                ('phone', models.CharField(max_length=17, verbose_name='Telefon raqami')),
                ('address', models.CharField(max_length=100, verbose_name='Manzili')),
                ('study_or_work_place', models.CharField(max_length=50, verbose_name="Ish yoki o'qish joyi")),
                ('lesson_time', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=15)),
                ('computer_knowledge', models.CharField(choices=[('0', 'Umuman bilmayman'), ('1', "O'rtacha bilaman"), ('2', 'Yaxshi bilaman')], max_length=1, verbose_name='Komputerdan bilimi')),
                ('programming_knowledge', models.CharField(choices=[('0', "Umuman tushuncha yo'q"), ('1', 'Ozroq xabari bor'), ('2', 'Kod yoza oladi')], max_length=1, verbose_name='Dasturlash tushunchasi')),
                ('has_computer', models.BooleanField(default=False, verbose_name='Shaxsiy kompyuteri bormi')),
                ('direction', models.CharField(choices=[('Programming', 'Programming'), ('Design', 'Design')], max_length=15, verbose_name="Yo'nalish")),
                ('filler', models.CharField(choices=[('Reception', 'Reception'), ('Self', 'Self')], max_length=20, verbose_name="Anketani to'ldiruvchi")),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Graduated', 'Graduated')], max_length=10)),
                ('lesson_time', models.TimeField(verbose_name='Dars vaqti')),
                ('lesson_days', models.CharField(choices=[('MWF', 'Dushanba-Chorshanba-Juma'), ('TTS', 'Seshanba-Payshanba-Shanba'), ('every', 'Har kuni')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='administration.courses')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='administration.rooms', verbose_name="Dars o'tiladigan xona")),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=17)),
                ('domain', models.URLField()),
                ('address', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('school_type', models.IntegerField(choices=[(1, 'EduAPP'), (2, 'Digital School')], default=2)),
                ('computers_qty', models.PositiveSmallIntegerField(default=0, verbose_name='Informatika sinfi kompyuterlari soni')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.districts')),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10, verbose_name='Status')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.schools')),
                ('specialty', models.ManyToManyField(related_name='teachers', to='administration.specializations', verbose_name='Mutaxassisliklari')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.staffs')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ism-familya')),
                ('phone', models.CharField(max_length=17)),
                ('birthdate', models.DateField(verbose_name="Tug'gilgan sana")),
                ('address', models.CharField(max_length=100, verbose_name='Manzili')),
                ('study_place', models.CharField(choices=[('school', 'school'), ('college', 'college'), ('university', 'university'), ('worker', 'worker')], max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], max_length=1, verbose_name='Jinsi')),
                ('passport', models.CharField(max_length=20, verbose_name='Pasport seria va raqami')),
                ('leaved_at', models.DateField(blank=True, null=True)),
                ('graduated_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Studying', 'Studying'), ('Graduated', 'Graduated'), ('Stopped', 'Stopped')], max_length=20)),
                ('first_month_price', models.PositiveIntegerField()),
                ('workplace_after_graduation', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='students')),
                ('qr_code', models.ImageField(upload_to='students/qr_codes')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='administration.districts', verbose_name='Tuman')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.groups', verbose_name='Guruhi')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.AddField(
            model_name='groups',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='school.schools'),
        ),
        migrations.AddField(
            model_name='groups',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='school.teachers', verbose_name="Guruh o'qituvchisi"),
        ),
    ]
